export enum Specialty {
    allergist = "allergist",                          // Bác sĩ chuyên khoa dị ứng
    andrologist = "andrologist",                      // Bác sĩ nam khoa
    anesthesiologist = "anesthesiologist",            // Bác sĩ gây mê
    cardiologist = "cardiologist",                    // Bác sĩ tim mạch
    dermatologist = "dermatologist",                  // Bác sĩ da liễu
    endocrinologist = "endocrinologist",              // Bác sĩ nội tiết
    epidemiologist = "epidemiologist",                // Bác sĩ dịch tễ học
    gastroenterologist = "gastroenterologist",        // Bác sĩ chuyên khoa tiêu hóa
    gynaecologist = "gynaecologist",                  // Bác sĩ phụ khoa
    haematologist = "haematologist",                  // Bác sĩ huyết học
    hepatologist = "hepatologist",                    // Bác sĩ chuyên khoa gan
    immunologist = "immunologist",                    // Bác sĩ chuyên khoa miễn dịch
    nephrologist = "nephrologist",                    // Bác sĩ chuyên khoa thận
    neurologist = "neurologist",                      // Bác sĩ chuyên khoa thần kinh
    oncologist = "oncologist",                        // Bác sĩ chuyên khoa ung thư
    ophthalmologist = "ophthalmologist",              // Bác sĩ mắt
    orthopedist = "orthopedist",                      // Bác sĩ ngoại chỉnh hình
    otorhinolaryngologist = "otorhinolaryngologist",  // Bác sĩ tai mũi họng
    otolaryngologist = "otolaryngologist",            // Bác sĩ tai mũi họng
    pathologist = "pathologist",                      // Bác sĩ bệnh lý học
    proctologist = "proctologist",                    // Bác sĩ chuyên khoa hậu môn – trực tràng
    psychiatrist = "psychiatrist",                    // Bác sĩ chuyên khoa tâm thần
    radiologist = "radiologist",                      // Bác sĩ X-quang
    rheumatologist = "rheumatologist",                // Bác sĩ chuyên khoa bệnh thấp
    traumatologist = "traumatologist",                // Bác sĩ chuyên khoa chấn thương
    obstetrician = "obstetrician",                    // Bác sĩ sản khoa
    paeditrician = "paeditrician"                     // Bác sĩ nhi khoa
}